language:
 - "python"
python:
  - "2.7"
before_install:
  - "sudo apt-get install libmysqlclient-dev"
install:
  - "pip install protobuf==3.2.0"
  - "python setup.py install"
script:
  - "python setup.py google_test --test-dir=tests/"
